resolver: lts-20.1
packages:
  - .
extra-deps:
  - hashable-1.3.5.0
  - rest-rewrite-0.4.1
  - smtlib-backends-0.3
  - smtlib-backends-process-0.3
  - liquidhaskell-boot-0.9.2.5.0
  - liquidhaskell-0.9.2.5.0
  - liquid-prelude-0.9.2.5
  - liquid-vector-0.12.3.1.2
  - liquid-fixpoint-0.9.2.5
  # - git: https://github.com/ucsd-progsys/liquidhaskell
  #   commit: fd5b5be4238cde87b012e105f16cb3bfe5a9dfe6
  #   subdirs:
  #     - .
  #     - liquidhaskell-boot
  #     - liquid-prelude
  #     - liquid-vector
  # - git: https://github.com/ucsd-progsys/liquid-fixpoint
  #   commit: 1ccf4b3962b4c3a3f4c17537280ec70edfa85c3e

# nix:
#   packages: [cacert, git, hostname, z3]
